#! /bin/bash

DOCKER_NAME="aws-env"
IMAGE_NAME="profile_lambda_update_user"
IMAGE_VERSION="0.0.2"
DOCKER_IMAGE=$IMAGE_NAME":"$IMAGE_VERSION
PATH_DIRECTORY=${PWD}
PROJECT_DIRECTORY=""
HOST_DIRECTORY="$PATH_DIRECTORY"
TARGET_DIRECTORY="/home"

docker rm -fv $DOCKER_NAME
docker run --name $DOCKER_NAME -p 9000:8080 $DOCKER_IMAGE
