name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Identify Changed Lambda Directories
        id: identify_changed_directories
        run: |
          # Verifica si hay al menos un commit previo
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            echo "Identifying changed directories since the last commit."
            # Identifica los directorios cambiados en la última confirmación
            git diff --name-only HEAD~1 HEAD lambdas/ > changed_files.txt
          else
            echo "No previous commits found. Listing all directories."
            # Si no hay commits previos, lista todos los directorios en lambdas/
            find lambdas -mindepth 1 -maxdepth 1 -type d > changed_files.txt
          fi

          echo "Changed directories:"
          cat changed_files.txt

      - name: Print Changed Lambda Directories (Debugging Step)
        run: |
          echo "Changed Lambda Directories:"
          cat changed_files.txt

      - name: Deploy Lambda Functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          cd lambdas
          # Itera sobre cada directorio de Lambda que ha cambiado
          cat ../changed_files.txt | while read -r lambda_dir; do
            echo "Deploying $lambda_dir"
            
            # Verifica si el directorio existe y contiene el archivo hello_world.py
            if [ -d "$lambda_dir" ] && [ -f "$lambda_dir/hello_world.py" ]; then
              echo "Found $lambda_dir with hello_world.py"
              # Crea el archivo ZIP para la Lambda
              zip -r "../${lambda_dir}.zip" "$lambda_dir/hello_world.py"
              # Sube el archivo ZIP a AWS Lambda
              aws lambda update-function-code --function-name "$lambda_dir" --zip-file "fileb://../${lambda_dir}.zip"
            else
              echo "Warning: Directory $lambda_dir does not exist or does not contain hello_world.py"
            fi
          done
