name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

    - name: Print changed files # Para depuración
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check if git_hub_actions_test Changed
      id: check_git_hub_actions_test
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^lambdas/git_hub_actions_test/'; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Deploy git_hub_actions_test Lambda
      if: env.changed == 'true'
      run: |
        LAMBDA_FUNCTION_NAME=git_hub_actions_test
        ZIP_FILE_NAME=git_hub_actions_test.zip
        # Change to the directory containing the Lambda function
        cd lambdas/git_hub_actions_test
        # Zip the contents of the current directory (without including the directory itself)
        zip -r ../../$ZIP_FILE_NAME .
        cd ../..
        # Update the Lambda function code
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ZIP_FILE_NAME
        # Cleanup
        rm $ZIP_FILE_NAME

    - name: Check if git_hub_actions_test_aux Changed
      id: check_git_hub_actions_test_aux
      run: |
        if git diff --name-only HEAD^ HEAD | grep -q '^lambdas/git_hub_actions_test_aux/'; then
          echo "changed=true" >> $GITHUB_ENV
        else
          echo "changed=false" >> $GITHUB_ENV
        fi

    - name: Deploy git_hub_actions_test_aux Lambda
      if: env.changed == 'true'
      run: |
        LAMBDA_FUNCTION_NAME=git_hub_actions_test_aux
        ZIP_FILE_NAME=git_hub_actions_test_aux.zip
        # Change to the directory containing the Lambda function
        cd lambdas/git_hub_actions_test_aux
        # Zip the contents of the current directory (without including the directory itself)
        zip -r ../../$ZIP_FILE_NAME .
        cd ../..
        # Update the Lambda function code
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ZIP_FILE_NAME
        # Cleanup
        rm $ZIP_FILE_NAME
