name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Cambia esto a la rama en la que quieras activar la acción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Zip Lambda Function
      run: zip -r function.zip hello_world.py

    - name: Upload to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        aws lambda update-function-code --function-name git_hub_actions_test --zip-file fileb://function.zip
