name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Print changed files
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/main' # Para producción
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/develop' # Para desarrollo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION_DEV }}

    - name: Install Dependencies
      run: |
        pip install flake8 black pytest pytest-cov coverage

    - name: Package Lambda function
      run: |
          mkdir -p package
          cp -r src/trips/publish_trips_test.py package/  # Copia tu función a la carpeta de paquete
          cd package
          zip -r ../lambda_function.zip .  # Empaqueta la función Lambda

    - name: Create Lambda function
      run: |
          aws lambda create-function \
            --function-name publish_trips_test \
            --zip-file fileb://lambda_function.zip \
            --handler publish_trips_test.lambda_handler \  # Ajusta esto según tu función
            --runtime python3.10 \  # O la versión que estés utilizando
            --role arn:aws:iam::682033485736:role/service-role/git_hub_actions_test-role-4qk5fqjf \  # Reemplaza con tu ARN de rol
            --timeout 30 \  # Ajusta según sea necesario
            --memory-size 128  # Ajusta según sea necesario
