name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Identify Changed Lambda Functions
        id: identify_changed_functions
        run: |
          # Verifica si hay al menos un commit previo
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            # Identifica los archivos cambiados en la última confirmación
            git diff --name-only HEAD~1 HEAD lambdas/ > changed_files.txt
          else
            # Si no hay commits previos, lista todos los archivos en lambdas/
            find lambdas -type f > changed_files.txt
          fi

      - name: Deploy Changed Lambda Functions
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Filtra y despliega las funciones Lambda que han tenido cambios
          while read -r changed_file; do
            # Extrae el nombre del directorio Lambda del archivo cambiado
            lambda_dir=$(dirname "$changed_file")
            lambda_name=$(basename "$lambda_dir")

            echo "Deploying $lambda_name"

            # Cambia al directorio de la función Lambda
            cd "$lambda_dir"

            # Crea el archivo ZIP para la Lambda
            zip -r "../${lambda_name}.zip" "lambda_function.py"

            # Regresa al directorio principal
            cd ..

            # Sube el archivo ZIP a AWS Lambda
            aws lambda update-function-code --function-name "$lambda_name" --zip-file "fileb://${lambda_name}.zip"
          done < changed_files.txt
