name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Print changed files
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/main' # Para producción
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/develop' # Para desarrollo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION_DEV }}

    - name: Install Dependencies
      run: |
        pip install flake8 black pytest pytest-cov coverage

    - name: Create Lambda Function
      run: |
        LAMBDA_NAME="publish_trips"
        
        # Empaquetar el código y crear el archivo ZIP
        zip -r9 lambda_function.zip src/trips/*

        # Crear la función Lambda si no existe
        if ! aws lambda get-function --function-name $LAMBDA_NAME; then
          echo "Creating Lambda Function: $LAMBDA_NAME"
          aws lambda create-function \
          --function-name my-function \
          --runtime nodejs10.x \
          --zip-file fileb://my-function.zip \
          --handler my-function.handler \
          --role arn:aws:iam::123456789012:role/service-role/MyTestFunction-role-tges6bf4
        else
          echo "Function $LAMBDA_NAME already exists. Exiting..."
        fi
