name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: List Lambda Directories
      id: list_directories
      run: |
        # Busca todas las subcarpetas en la carpeta lambdas
        find lambdas -mindepth 1 -maxdepth 1 -type d -printf '%f\n' > lambda_directories.txt

    - name: Deploy Lambda Functions
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        # Itera sobre cada carpeta encontrada
        while read -r lambda_dir; do
          # Define la ruta completa del archivo de la función Lambda
          lambda_file="lambdas/${lambda_dir}/hello_world.py"
          # Define el nombre de la función Lambda como el nombre de la carpeta
          lambda_name="${lambda_dir}"

          echo "Deploying $lambda_name"

          # Crea el archivo ZIP para la Lambda
          zip -r "${lambda_name}.zip" "$lambda_file"

          # Sube el archivo ZIP a AWS Lambda
          aws lambda update-function-code --function-name "$lambda_name" --zip-file "fileb://${lambda_name}.zip"
        done < lambda_directories.txt
