name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Identify Changed Lambda Functions
      id: identify_changed_functions
      run: |
        # Identifica los archivos cambiados en la última confirmación
        git diff --name-only HEAD~1 HEAD lambdas/ > changed_files.txt

        # Extrae los directorios únicos de las funciones Lambda que han cambiado
        awk -F'/' '{print $2}' changed_files.txt | sort | uniq > changed_lambdas.txt

    - name: Print Changed Lambdas (Debugging Step)
      run: |
        echo "Changed Lambdas:"
        cat changed_lambdas.txt

    - name: Deploy Lambda Functions
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        cd lambdas
        # Itera sobre cada carpeta de Lambda que ha cambiado
        while read -r lambda_dir; do
          # Define el nombre de la función Lambda como el nombre de la carpeta
          lambda_name="${lambda_dir}"
          echo "Deploying $lambda_name"
          
          # Verifica si el directorio existe y contiene el archivo lambda_function.py
          if [ -d "$lambda_dir" ] && [ -f "$lambda_dir/lambda_function.py" ]; then
            # Cambia al directorio de la función Lambda
            cd "$lambda_dir"
            # Crea el archivo ZIP para la Lambda
            zip -r "../${lambda_name}.zip" "lambda_function.py"
            # Regresa al directorio principal
            cd ..
            # Sube el archivo ZIP a AWS Lambda
            aws lambda update-function-code --function-name "$lambda_name" --zip-file "fileb://${lambda_name}.zip"
          else
            echo "Warning: Directory $lambda_dir does not exist or does not contain lambda_function.py"
          fi
        done < ../changed_lambdas.txt
