name: Deploy Lambda Functions

on:
  push:
    branches:
      - main  # Cambia esto a la rama en la que quieras activar la acción

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install

    - name: Determine changed Lambda functions
      id: changes
      run: |
        echo "CHANGED_LAMBDAS=$(git diff --name-only HEAD~1 HEAD | grep 'lambda_functions/' | cut -d/ -f2,3 | sort | uniq)" >> $GITHUB_ENV
        echo "Changed Lambda functions: $CHANGED_LAMBDAS"
    
    - name: Deploy changed Lambda functions
      if: env.CHANGED_LAMBDAS != ''
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        for lambda in $CHANGED_LAMBDAS; do
          FUNCTION_NAME=$(echo $lambda | cut -d/ -f1)
          ZIP_FILE="${FUNCTION_NAME}.zip"
          zip -r $ZIP_FILE "lambda_functions/$lambda"
          aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://$ZIP_FILE
        done
