name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

    - name: Print changed files # To properly debug what is being deployed (It can be removed).
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy git_hub_actions_test Lambda
      run: |
        LAMBDA_FUNCTION_NAME=git_hub_actions_test
        ZIP_FILE_NAME=git_hub_actions_test.zip
        # Zip the contents of the lambdas/git_hub_actions_test directory
        zip -r $ZIP_FILE_NAME lambdas/git_hub_actions_test
        # Update the Lambda function code
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ZIP_FILE_NAME
        # Cleanup
        rm $ZIP_FILE_NAME

    - name: Deploy git_hub_actions_test_aux Lambda
      run: |
        LAMBDA_FUNCTION_NAME=git_hub_actions_test_aux
        ZIP_FILE_NAME=git_hub_actions_test_aux.zip
        # Zip the contents of the lambdas/git_hub_actions_test_aux directory
        zip -r $ZIP_FILE_NAME lambdas/git_hub_actions_test_aux
        # Update the Lambda function code
        aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://$ZIP_FILE_NAME
        # Cleanup
        rm $ZIP_FILE_NAME
