name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Print changed files
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/main' # Para producción
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/develop' # Para desarrollo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION_DEV }}

    - name: Install Dependencies
      run: |
        pip install flake8 black pytest pytest-cov coverage

    - name: Create ZIP for Lambda
      run: |
          # Cambia al directorio que contiene tu archivo
          cd src/trips/
          # Crea el archivo ZIP
          zip -r ../lambda_function.zip publish_trips_test.py
          # Lista los archivos en el directorio padre para verificar que el ZIP se ha creado
          ls -l ../

    - name: Check if Lambda function exists
      id: check-lambda
      run: |
            if aws lambda get-function --function-name publish_trips_test; then
              echo "exists=true" >> $GITHUB_ENV
            else
              echo "exists=false" >> $GITHUB_ENV
            fi

    - name: Create or Update Lambda function
      run: |
                if [ "$exists" == "true" ]; then
                  echo "Updating existing Lambda function"
                  aws lambda update-function-code \
                    --function-name publish_trips_test \
                    --zip-file fileb://src/lambda_function.zip
                else
                  echo "Creating new Lambda function"
                  aws lambda create-function \
                  --function-name publish_trips_test \
                  --zip-file fileb://src/lambda_function.zip \
                  --handler src.trips.publish_trips_test.lambda_handler \
                  --runtime python3.10 \
                  --role arn:aws:iam::682033485736:role/service-role/git_hub_actions_test-role-4qk5fqjf \
                  --timeout 30 \
                  --memory-size 128
                fi
