name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Print changed files
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/main' # Para producción
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/develop' # Para desarrollo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION_DEV }}

    - name: Install Dependencies
      run: |
        pip install flake8 black pytest pytest-cov coverage

    - name: Create Lambda Function
      run: |
        LAMBDA_NAME="publish_trips"
        
        # Empaquetar el código y crear el archivo ZIP
        zip -r9 lambda_function.zip src/trips/*

        # Crear la función Lambda si no existe
        if ! aws lambda get-function --function-name $LAMBDA_NAME; then
          echo "Creating Lambda Function: $LAMBDA_NAME"
          aws lambda create-function \
            --function-name $LAMBDA_NAME \
            --runtime python3.10 \  # Cambia a la versión de runtime que necesites
            --role arn:aws:iam::682033485736:role/service-role/git_hub_actions_test-role-4qk5fqjf \  # Verifica que el ARN del rol sea correcto
            --handler publish_trips_test.lambda_handler \  # Asegúrate de que esto coincida con tu archivo y función
            --zip-file fileb://lambda_function.zip \
            --timeout 15 \  # Establece un timeout si es necesario
            --memory-size 128  # Ajusta la memoria si es necesario
        else
          echo "Function $LAMBDA_NAME already exists. Exiting..."
        fi
