name: Deploy Lambda Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 # To fetch the current commit and its parent (so we can compare)

    - name: Print changed files # Para depuración
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Install Dependencies
      run: |
        pip install flake8 black  # Instala flake8 para chequeo de estilo y black para formateo

    - name: Check Code Style with flake8
      run: |
        flake8 lambdas/  # Ajusta el directorio según donde se encuentren tus funciones Lambda

    - name: Format Code with black
      run: |
          black lambdas/  # Formatear automáticamente el código

    
    - name: Run Tests with Coverage
      run: |
            coverage run -m pytest
            coverage report -m
            coverage report | tee coverage.txt
    
    - name: Check Coverage
      run: |
            threshold=80
            coverage_percentage=$(coverage report | tail -n +3 | awk '{ print $NF }' | grep -vE '^$' | sed 's/%//')
            if (( $(echo "$coverage_percentage < $threshold" | bc -l) )); then
              echo "Coverage threshold not met: $coverage_percentage%"
              exit 1
            fi

    - name: Find and Deploy Changed Lambda Functions
      run: |
        # Find all the Lambda function directories that have changes
        changed_lambdas=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | cut -d '/' -f 2-3 | uniq)
        echo "Changed Lambda Directories: $changed_lambdas"
        for lambda in $changed_lambdas; do
          # Extract the directory and function name from the path
          dir_name=$(echo $lambda | cut -d '/' -f 1)
          function_name=$(echo $lambda | cut -d '/' -f 2)
          zip_file_name=${function_name}.zip
          
          # Only proceed if there are Python files that have changed
          if git diff --name-only HEAD^ HEAD | grep -q "^lambdas/${dir_name}/${function_name}/.*\.py$"; then
            echo "Changes detected in Lambda function: $function_name"
            # Change to the directory containing the Lambda function
            cd lambdas/$dir_name/$function_name
            
            # Zip the contents of the current directory (without including the directory itself)
            zip -r ../../../$zip_file_name .
            
            # Go back to the root directory
            cd ../../../
            
            # Update the Lambda function code
            aws lambda update-function-code --function-name $function_name --zip-file fileb://$zip_file_name
            
            # Cleanup
            rm $zip_file_name
          else
            echo "No Python file changes detected in $function_name, skipping deployment."
          fi
        done
