name: Deploy Lambda Functions

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Print changed files
      run: |
        echo "List of changed files:" 
        echo $(git diff --name-only HEAD^ HEAD)

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/main' # Para producción
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set AWS Credentials Based on Branch
      if: github.ref == 'refs/heads/develop' # Para desarrollo
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ${{ secrets.AWS_REGION_DEV }}

    - name: Install Dependencies
      run: |
        pip install flake8 black pytest pytest-cov coverage

    - name: Check Code Style with flake8
      run: |
        flake8 lambdas/

    - name: Format Code with black
      run: |
        black lambdas/

    - name: Find and Deploy Changed Lambda Functions
      run: |
        changed_lambdas=$(git diff --name-only HEAD^ HEAD | grep '^lambdas/' | cut -d '/' -f 2-3 | uniq)
        echo "Changed Lambda Directories: $changed_lambdas"
        for lambda in $changed_lambdas; do
          dir_name=$(echo $lambda | cut -d '/' -f 1)
          function_name=$(echo $lambda | cut -d '/' -f 2)
          zip_file_name=${function_name}.zip

          if git diff --name-only HEAD^ HEAD | grep -q "^lambdas/${dir_name}/${function_name}/.*\.py$"; then
            echo "Changes detected in Lambda function: $function_name"
            cd lambdas/$dir_name/$function_name
            zip -r ../../../$zip_file_name .
            cd ../../../
            aws lambda update-function-code --function-name $function_name --zip-file fileb://$zip_file_name
            rm $zip_file_name
          else
            echo "No Python file changes detected in $function_name, skipping deployment."
          fi
        done
